Using the Mental Health dataset and what you have learn this week, answer the following questions :

What is the distribution of mental health conditions among different age groups in the tech industry?
How does the frequency of mental health issues vary by gender?
Identify the countries with the highest and lowest reported rates of mental health issues in the tech industry.

Introduction to the Dataset:

Download the dataset from Kaggle.
Load the dataset using Pandas.
Perform initial exploration to understand the dataset structure : whats the distribution of the data? What types of data do i have?
Data Cleaning:

Identify and handle missing values.
Detect and correct any inconsistencies in the data.
Drop irrelevant columns if necessary.

In [1]:
import pandas as pd
df = pd.read_csv('/content/survey.csv')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Timestamp                  1259 non-null   object
 1   Age                        1259 non-null   int64
 2   Gender                     1259 non-null   object
 3   Country                    1259 non-null   object
 4   state                      744 non-null    object
 5   self_employed              1241 non-null   object
 6   family_history             1259 non-null   object
 7   treatment                  1259 non-null   object
 8   work_interfere             995 non-null    object
 9   no_employees               1259 non-null   object
 10  remote_work                1259 non-null   object
 11  tech_company               1259 non-null   object
 12  benefits                   1259 non-null   object
 13  care_options               1259 non-null   object
 14  wellness_program           1259 non-null   object
 15  seek_help                  1259 non-null   object
 16  anonymity                  1259 non-null   object
 17  leave                      1259 non-null   object
 18  mental_health_consequence  1259 non-null   object
 19  phys_health_consequence    1259 non-null   object
 20  coworkers                  1259 non-null   object
 21  supervisor                 1259 non-null   object
 22  mental_health_interview    1259 non-null   object
 23  phys_health_interview      1259 non-null   object
 24  mental_vs_physical         1259 non-null   object
 25  obs_consequence            1259 non-null   object
 26  comments                   164 non-null    object
dtypes: int64(1), object(26)
memory usage: 265.7+ KB

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

Data Cleaning

In [2]:
columns_to_drop = [
    'Timestamp', 'state', 'self_employed', 'comments', 'no_employees', 'remote_work',
    'tech_company', 'benefits', 'care_options', 'wellness_program', 'seek_help',
    'anonymity', 'leave', 'mental_health_consequence', 'phys_health_consequence',
    'coworkers', 'supervisor', 'mental_health_interview', 'phys_health_interview',
    'mental_vs_physical', 'obs_consequence'
]
df_cleaned = df.drop(columns=columns_to_drop)
df_cleaned['work_interfere'] = df_cleaned['work_interfere'].fillna('Unknown')
df_cleaned = df_cleaned[(df_cleaned['Age'] >= 18) & (df_cleaned['Age'] <= 100)]

def clean_gender(gender):
    gender = gender.lower()
    if 'female' in gender or 'f' in gender:
        return 'Female'
    elif 'male' in gender or 'm' in gender:
        return 'Male'
    else:
        return 'Other'

df_cleaned['Gender'] = df_cleaned['Gender'].apply(clean_gender)

print(df_cleaned.info())
print(df_cleaned.head())

<class 'pandas.core.frame.DataFrame'>
Index: 1251 entries, 0 to 1258
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             1251 non-null   int64
 1   Gender          1251 non-null   object
 2   Country         1251 non-null   object
 3   family_history  1251 non-null   object
 4   treatment       1251 non-null   object
 5   work_interfere  1251 non-null   object
dtypes: int64(1), object(5)
memory usage: 68.4+ KB
None
   Age  Gender         Country family_history treatment work_interfere
0   37  Female   United States             No       Yes          Often
1   44    Male   United States             No        No         Rarely
2   32    Male          Canada             No        No         Rarely
3   31    Male  United Kingdom            Yes       Yes          Often
4   31    Male   United States             No        No          Never

What is the distribution of mental health conditions among different age groups in the tech industry?

In [3]:
bins = [0, 25, 35, 45, 55, 65, 100]
labels = ['<25', '25-34', '35-44', '45-54', '55-64', '65+']
df_cleaned['age_group'] = pd.cut(df_cleaned['Age'], bins=bins, labels=labels, right=False)

age_group_distribution = df_cleaned.groupby('age_group')['treatment'].value_counts(normalize=True).unstack().fillna(0)

print(age_group_distribution)

treatment        No       Yes
age_group
<25        0.551282  0.448718
25-34      0.510608  0.489392
35-44      0.453125  0.546875
45-54      0.431373  0.568627
55-64      0.266667  0.733333
65+        0.500000  0.500000

<ipython-input-3-7e69ce4df1f1>:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  age_group_distribution = df_cleaned.groupby('age_group')['treatment'].value_counts(normalize=True).unstack().fillna(0)

How does the frequency of mental health issues vary by gender?

In [4]:
gender_freq = df_cleaned.groupby('Gender')['treatment'].value_counts(normalize=True).unstack().fillna(0)

print(gender_freq)

treatment        No       Yes
Gender
Female     0.307692  0.692308
Male       0.545272  0.454728
Other      0.100000  0.900000

Identify the countries with the highest and lowest reported rates of mental health issues in the tech industry.

In [5]:
country_distribution = df_cleaned.groupby('Country')['treatment'].value_counts(normalize=True).unstack().fillna(0)
country_distribution['Rate'] = country_distribution['Yes']

highest_countries = country_distribution['Rate'].nlargest(5)
lowest_countries = country_distribution['Rate'].nsmallest(5)

print("Countries with highest rate:")
print(highest_countries)

print("\nCountries with lowest rate:")
print(lowest_countries)

Countries with highest rate:
Country
Croatia     1.0
Denmark     1.0
Japan       1.0
Moldova     1.0
Slovenia    1.0
Name: Rate, dtype: float64

Countries with lowest rate:
Country
Austria                   0.0
Bosnia and Herzegovina    0.0
China                     0.0
Colombia                  0.0
Costa Rica                0.0
Name: Rate, dtype: float64